"""add_new_schemas

Revision ID: 150dfa04b086
Revises: c8d4e9f1a2b3
Create Date: 2026-09-25 13:32:10.545183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '150dfa04b086'
down_revision: Union[str, Sequence[str], None] = 'c8d4e9f1a2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'offer_versions',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('version', sa.String(length=32), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_offer_versions')),
    )

    op.create_table(
        'kyc_data',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('kyc_level', sa.String(length=32), nullable=True),
        sa.Column('kyc_status', sa.Boolean(), server_default=sa.text('false'), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_kyc_data_user_id_users'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_kyc_data')),
        sa.UniqueConstraint('user_id', name=op.f('uq_kyc_data_user_id')),
    )

    op.add_column(
        'orders',
        sa.Column(
            'order_type',
            sa.Enum('subscriptions', 'tickets_and_reservations', 'free_deal', name='order_types', native_enum=False, create_constraint=True),
            server_default='free_deal',
            nullable=False,
        ),
    )
    op.alter_column('orders', 'order_type', server_default=None)

    op.add_column('orders', sa.Column('source_of_truth', sa.String(length=500), nullable=True))
    op.add_column('orders', sa.Column('site_or_app', sa.String(length=500), nullable=True))
    op.add_column('orders', sa.Column('customer_identity', sa.String(length=500), nullable=True))
    op.add_column('orders', sa.Column('additional_requirements', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('contact_free_deal', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('task_free_deal', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('how_to_proove_free_deal', sa.Text(), nullable=True))
    op.create_index('ix_orders_order_type', 'orders', ['order_type'], unique=False)
    op.drop_column('orders', 'result_requirements')
    op.drop_column('orders', 'conditions')

    op.add_column('users', sa.Column('patronymic', sa.String(length=128), server_default='', nullable=False))
    op.alter_column('users', 'patronymic', server_default=None)

    op.add_column('users', sa.Column('birth_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'birth_date', server_default=None)

    op.add_column('users', sa.Column('persondoc_number', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('month_sum_limit', sa.Numeric(precision=12, scale=2), server_default='200000.00', nullable=False))
    op.create_unique_constraint(op.f('uq_users_persondoc_number'), 'users', ['persondoc_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_persondoc_number'), 'users', type_='unique')
    op.drop_column('users', 'month_sum_limit')
    op.drop_column('users', 'persondoc_number')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'patronymic')

    op.add_column('orders', sa.Column('conditions', sa.TEXT(), server_default='', nullable=False))
    op.add_column('orders', sa.Column('result_requirements', sa.TEXT(), server_default='', nullable=False))
    op.alter_column('orders', 'conditions', server_default=None)
    op.alter_column('orders', 'result_requirements', server_default=None)

    op.drop_index('ix_orders_order_type', table_name='orders')
    op.drop_column('orders', 'how_to_proove_free_deal')
    op.drop_column('orders', 'task_free_deal')
    op.drop_column('orders', 'contact_free_deal')
    op.drop_column('orders', 'additional_requirements')
    op.drop_column('orders', 'customer_identity')
    op.drop_column('orders', 'site_or_app')
    op.drop_column('orders', 'source_of_truth')
    op.drop_column('orders', 'order_type')

    op.drop_table('kyc_data')
    op.drop_table('offer_versions')
    # ### end Alembic commands ###
