"""delete excess fields

Revision ID: 3156bde2c77b
Revises: f6a2b7c9d4e1
Create Date: 2026-06-11 10:47:36.738167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3156bde2c77b'
down_revision: Union[str, Sequence[str], None] = 'f6a2b7c9d4e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders_payment_data', 'performer_payout_url')
    op.drop_column('orders_payment_data', 'funds_frozen_at')
    op.drop_column('orders_payment_data', 'payout_link_created_at')
    op.drop_column('orders_payment_data', 'customer_payment_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_payment_data', sa.Column('customer_payment_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('orders_payment_data', sa.Column('payout_link_created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('orders_payment_data', sa.Column('funds_frozen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('orders_payment_data', sa.Column('performer_payout_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
