"""base_revision

Revision ID: 8fae72cbed2d
Revises: 
Create Date: 2026-05-22 16:34:35.523530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fae72cbed2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('ppd', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('role', sa.Enum('performer', 'client', name='user_roles', native_enum=False, create_constraint=True), server_default='client', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('phone_number', name=op.f('uq_users_phone_number'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('order', 'review', 'promotion', 'news', name='notification_types', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('unread', 'read', 'archived', 'failed', name='notification_statuses', native_enum=False, create_constraint=True), server_default='unread', nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_status', 'notifications', ['status'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_status_created_at', 'notifications', ['user_id', 'status', 'created_at'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('performer_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=False),
    sa.Column('result_requirements', sa.Text(), nullable=False),
    sa.Column('violation_proof_requirements', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('awaiting_performer', 'awaiting_payment', 'awaiting_performer_confirmation', 'awaiting_client_confirmation', 'awaiting_conflict', 'open_conflict', 'successful_completion', 'unsuccessful_completion', 'closed_by_arbiter_to_client', 'closed_by_arbiter_to_performer', name='order_states', native_enum=False, create_constraint=True), server_default='awaiting_performer', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name=op.f('fk_orders_client_id_users')),
    sa.ForeignKeyConstraint(['performer_id'], ['users.id'], name=op.f('fk_orders_performer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('slug', name=op.f('uq_orders_slug'))
    )
    op.create_index('ix_orders_client_id', 'orders', ['client_id'], unique=False)
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('ix_orders_performer_id', 'orders', ['performer_id'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_table('order_status_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('old_status', sa.Enum('awaiting_performer', 'awaiting_payment', 'awaiting_performer_confirmation', 'awaiting_client_confirmation', 'awaiting_conflict', 'open_conflict', 'successful_completion', 'unsuccessful_completion', 'closed_by_arbiter_to_client', 'closed_by_arbiter_to_performer', name='order_history_old_states', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('new_status', sa.Enum('awaiting_performer', 'awaiting_payment', 'awaiting_performer_confirmation', 'awaiting_client_confirmation', 'awaiting_conflict', 'open_conflict', 'successful_completion', 'unsuccessful_completion', 'closed_by_arbiter_to_client', 'closed_by_arbiter_to_performer', name='order_history_new_states', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('changed_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], name=op.f('fk_order_status_history_changed_by_user_id_users')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_status_history_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_status_history'))
    )
    op.create_index('ix_order_status_history_created_at', 'order_status_history', ['created_at'], unique=False)
    op.create_index('ix_order_status_history_order_id', 'order_status_history', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_status_history_order_id', table_name='order_status_history')
    op.drop_index('ix_order_status_history_created_at', table_name='order_status_history')
    op.drop_table('order_status_history')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_performer_id', table_name='orders')
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.drop_index('ix_orders_client_id', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_notifications_user_status_created_at', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_index('ix_notifications_status', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('users')
    # ### end Alembic commands ###
