"""add new colums

Revision ID: cd4c5cfb6958
Revises: 8fae72cbed2d
Create Date: 2026-05-30 10:05:02.026884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd4c5cfb6958'
down_revision: Union[str, Sequence[str], None] = '8fae72cbed2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_status_history', 'old_status',
               existing_type=sa.VARCHAR(length=31),
               type_=sa.Enum('awaiting_performer', 'awaiting_payment', 'awaiting_performer_confirmation', 'awaiting_client_confirmation', 'awaiting_conflict', 'open_conflict', 'successful_completion', 'unsuccessful_completion', 'cancled_by_expire_time_to_client', 'confirm_by_expire_time_to_performer', 'closed_by_arbiter_to_client', 'closed_by_arbiter_to_performer', name='order_history_old_states', native_enum=False, create_constraint=True),
               existing_nullable=True)
    op.alter_column('order_status_history', 'new_status',
               existing_type=sa.VARCHAR(length=31),
               type_=sa.Enum('awaiting_performer', 'awaiting_payment', 'awaiting_performer_confirmation', 'awaiting_client_confirmation', 'awaiting_conflict', 'open_conflict', 'successful_completion', 'unsuccessful_completion', 'cancled_by_expire_time_to_client', 'confirm_by_expire_time_to_performer', 'closed_by_arbiter_to_client', 'closed_by_arbiter_to_performer', name='order_history_new_states', native_enum=False, create_constraint=True),
               existing_nullable=False)
    op.add_column('orders', sa.Column('checked_by_worker_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('orders', sa.Column('expire_in', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=31),
               type_=sa.Enum('awaiting_performer', 'awaiting_payment', 'awaiting_performer_confirmation', 'awaiting_client_confirmation', 'awaiting_conflict', 'open_conflict', 'successful_completion', 'unsuccessful_completion', 'cancled_by_expire_time_to_client', 'confirm_by_expire_time_to_performer', 'closed_by_arbiter_to_client', 'closed_by_arbiter_to_performer', name='order_states', native_enum=False, create_constraint=True),
               existing_nullable=False,
               existing_server_default=sa.text("'awaiting_performer'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('awaiting_performer', 'awaiting_payment', 'awaiting_performer_confirmation', 'awaiting_client_confirmation', 'awaiting_conflict', 'open_conflict', 'successful_completion', 'unsuccessful_completion', 'cancled_by_expire_time_to_client', 'confirm_by_expire_time_to_performer', 'closed_by_arbiter_to_client', 'closed_by_arbiter_to_performer', name='order_states', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=31),
               existing_nullable=False,
               existing_server_default=sa.text("'awaiting_performer'::character varying"))
    op.drop_column('orders', 'expire_in')
    op.drop_column('orders', 'checked_by_worker_at')
    op.alter_column('order_status_history', 'new_status',
               existing_type=sa.Enum('awaiting_performer', 'awaiting_payment', 'awaiting_performer_confirmation', 'awaiting_client_confirmation', 'awaiting_conflict', 'open_conflict', 'successful_completion', 'unsuccessful_completion', 'cancled_by_expire_time_to_client', 'confirm_by_expire_time_to_performer', 'closed_by_arbiter_to_client', 'closed_by_arbiter_to_performer', name='order_history_new_states', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=31),
               existing_nullable=False)
    op.alter_column('order_status_history', 'old_status',
               existing_type=sa.Enum('awaiting_performer', 'awaiting_payment', 'awaiting_performer_confirmation', 'awaiting_client_confirmation', 'awaiting_conflict', 'open_conflict', 'successful_completion', 'unsuccessful_completion', 'cancled_by_expire_time_to_client', 'confirm_by_expire_time_to_performer', 'closed_by_arbiter_to_client', 'closed_by_arbiter_to_performer', name='order_history_old_states', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=31),
               existing_nullable=True)
    # ### end Alembic commands ###
