from decimal import Decimal
from os import getenv
from pathlib import Path

from dotenv import load_dotenv


load_dotenv(Path(__file__).resolve().parents[1] / ".env")

JWT_SECRET_KEY = getenv("JWT_SECRET_KEY")
JWT_ALGORITHM = getenv("JWT_ALGORITHM")
JWT_ACCESS_TOKEN_EXPIRE_MINUTES = getenv("JWT_ACCESS_TOKEN_EXPIRE_MINUTES")
JWT_REFRESH_TOKEN_EXPIRE_MINUTES = getenv("JWT_REFRESH_TOKEN_EXPIRE_MINUTES")
BASE_SITE_LINK = getenv("BASE_SITE_LINK")
EXPIRE_TIME_TO_COMNFIRM_MINUTES = getenv("EXPIRE_TIME_TO_COMNFIRM_MINUTES")
ADMIN_PASSWORD_PEPPER = getenv("ADMIN_PASSWORD_PEPPER")
MAX_SINGLE_ORDER_PRICE = getenv("MAX_SINGLE_ORDER_PRICE")
VERIFICATION_REQUIRED_PRICE_THRESHOLD = getenv("VERIFICATION_REQUIRED_PRICE_THRESHOLD")

if not JWT_SECRET_KEY:
    raise RuntimeError("JWT_SECRET_KEY is not set")

if not JWT_ALGORITHM:
    raise RuntimeError("JWT_ALGORITHM is not set")

if not JWT_ACCESS_TOKEN_EXPIRE_MINUTES:
    raise RuntimeError("JWT_ACCESS_TOKEN_EXPIRE_MINUTES is not set")

if not JWT_REFRESH_TOKEN_EXPIRE_MINUTES:
    raise RuntimeError("JWT_REFRESH_TOKEN_EXPIRE_MINUTES is not set")

if not BASE_SITE_LINK:
    raise RuntimeError("BASE_SITE_LINK is not set")

if not EXPIRE_TIME_TO_COMNFIRM_MINUTES:
    raise RuntimeError("EXPIRE_TIME_TO_COMNFIRM_MINUTES is not set")

if not ADMIN_PASSWORD_PEPPER:
    raise RuntimeError("ADMIN_PASSWORD_PEPPER is not set")

if not MAX_SINGLE_ORDER_PRICE:
    raise RuntimeError("MAX_SINGLE_ORDER_PRICE is not set")

if not VERIFICATION_REQUIRED_PRICE_THRESHOLD:
    raise RuntimeError("VERIFICATION_REQUIRED_PRICE_THRESHOLD is not set")

JWT_ACCESS_TOKEN_EXPIRE_MINUTES = int(JWT_ACCESS_TOKEN_EXPIRE_MINUTES)
JWT_REFRESH_TOKEN_EXPIRE_MINUTES = int(JWT_REFRESH_TOKEN_EXPIRE_MINUTES)
JWT_ALGORITHM = str(JWT_ALGORITHM)
JWT_SECRET_KEY = str(JWT_SECRET_KEY)
BASE_SITE_LINK = str(BASE_SITE_LINK)
EXPIRE_TIME_TO_COMNFIRM_MINUTES = Decimal(EXPIRE_TIME_TO_COMNFIRM_MINUTES)
ADMIN_PASSWORD_PEPPER = str(ADMIN_PASSWORD_PEPPER)
MAX_SINGLE_ORDER_PRICE = Decimal(MAX_SINGLE_ORDER_PRICE)
VERIFICATION_REQUIRED_PRICE_THRESHOLD = Decimal(VERIFICATION_REQUIRED_PRICE_THRESHOLD)

